apiVersion: v1
kind: Namespace
metadata:
  name: perebityuk
  labels:
    app: nginx

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: perebityuk
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: http-conf
          subPath: http.conf
          mountPath: /etc/nginx/conf.d/default.conf

      - name: nginx-exporter
        image: 'nginx/nginx-prometheus-exporter:0.11.0'
        imagePullPolicy: "IfNotPresent"
        args:
          - '-nginx.scrape-uri=http://localhost/basic_status'
        resources:
            limits:
              memory: 128Mi
              cpu: 500m
        ports:
          - containerPort: 9113
            name: mon
      volumes:
      - name: http-conf
        configMap:
          name: nginx-config
          defaultMode: 420


---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: nginx
  namespace: perebityuk
  name: nginx-config
data:
  http.conf: |
    server {
        listen       80;
        server_name  localhost;
        location = /basic_status {
            stub_status;
        }
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: perebityuk
  labels:
    app: nginx
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9113'
    prometheus.io/scheme: http
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: mon
    port: 9113
    protocol: TCP
    targetPort: mon
  selector:
   app: nginx
